// Exemplos da galeria. Para adicionar mais, inclua um item aqui ou no arquivo gallery.json (mesmo formato).
var GALLERY = [
  { title: "Black Friday", author: "Gerart",
    shared: { brand: "SUPER LOJA", name: "BLACK FRIDAY", desc: "Descontos de até 70% só hoje.", oldPrice: "R$ 299,00", price: "R$ 149,90", cta: "Aproveite agora",
      font: "Impact", stops: [{ c: "#000000" }, { c: "#2b2b2b" }], bgAngle: 180, accent: "#ffd400", ctaText: "#000000", nameSize: 120 } },
  { title: "Moda feminina", author: "Gerart",
    shared: { brand: "BELLA MODA", name: "Coleção Verão", desc: "Peças leves para os dias de sol.", price: "R$ 89,90", cta: "Ver coleção",
      font: "Georgia", stops: [{ c: "#ff9a9e" }, { c: "#fad0c4" }, { c: "#fbc2eb" }], bgAngle: 150, textColor: "#3a1230", accent: "#c2185b", ctaText: "#ffffff" } },
  { title: "Delivery de comida", author: "Gerart",
    shared: { brand: "BURGER HOUSE", name: "Combo Duplo", desc: "Dois burgers, batata e refri.", price: "R$ 39,90", cta: "Peça já",
      font: "Arial Black", stops: [{ c: "#f12711" }, { c: "#f5af19" }], bgAngle: 160, accent: "#ffffff", ctaText: "#b71c1c", nameSize: 96 } },
  { title: "Tecnologia", author: "Gerart",
    shared: { brand: "TECHNO", name: "Fone Bluetooth", desc: "Som potente e 30h de bateria.", oldPrice: "R$ 249,00", price: "R$ 179,90", cta: "Compre agora",
      font: "Trebuchet MS", stops: [{ c: "#0f2027" }, { c: "#203a43" }, { c: "#2c5364" }], bgAngle: 170, accent: "#00e5ff", ctaText: "#00212b" } },
  { title: "Natureza e bem-estar", author: "Gerart",
    shared: { brand: "VIDA VERDE", name: "Kit Orgânico", desc: "Direto da horta para sua casa.", price: "R$ 59,90", cta: "Quero o meu",
      font: "Verdana", stops: [{ c: "#134e5e" }, { c: "#71b280" }], bgAngle: 160, accent: "#fff176", ctaText: "#134e5e", nameSize: 76 } },
  { title: "Minimalista claro", author: "Gerart",
    shared: { brand: "ATELIÊ", name: "Nova Linha", desc: "Design simples, qualidade de sobra.", price: "R$ 120,00", cta: "Saiba mais",
      font: "Segoe UI", stops: [{ c: "#f5f7fa" }, { c: "#c3cfe2" }], bgAngle: 160, textColor: "#1c1c28", accent: "#1c1c28", ctaText: "#ffffff" } },
  { title: "Neon gamer", author: "Gerart",
    shared: { brand: "PIXEL ZONE", name: "HEADSET PRO X", desc: "Áudio 7.1 e microfone com cancelamento de ruído.", oldPrice: "R$ 399,00", price: "R$ 289,90", cta: "GARANTIR O MEU",
      font: "Courier New", stops: [{ c: "#0d0221" }, { c: "#3a0ca3" }, { c: "#f72585" }], bgAngle: 200, align: "left", textColor: "#e0fbff", accent: "#39ff14", ctaText: "#0d0221", nameSize: 90, priceSize: 120 } },
  { title: "Café artesanal", author: "Gerart",
    shared: { brand: "GRÃO NOBRE", name: "Café Especial 250g", desc: "Torra média, notas de chocolate e caramelo.", price: "R$ 34,90", cta: "Experimente",
      font: "Georgia", stops: [{ c: "#3e2723" }, { c: "#6d4c41" }, { c: "#d7b899" }], bgAngle: 175, align: "left", textColor: "#fff3e0", accent: "#ffcc80", ctaText: "#3e2723", nameSize: 78, priceSize: 110, imgPos: "bottom" } },
  { title: "Fitness energia", author: "Gerart",
    shared: { brand: "FIT POWER", name: "MATRÍCULA GRÁTIS", desc: "Treine este mês sem pagar adesão.", oldPrice: "R$ 150,00", price: "R$ 0,00", cta: "Começar agora",
      font: "Impact", stops: [{ c: "#00c6ff" }, { c: "#0072ff" }], bgAngle: 135, align: "right", textColor: "#ffffff", accent: "#c6ff00", ctaText: "#002b5c", nameSize: 110, descSize: 40 } },
  { title: "Imobiliária de luxo", author: "Gerart",
    shared: { brand: "ALTO PADRÃO IMÓVEIS", name: "Cobertura Duplex", desc: "4 suítes · 3 vagas · Vista para o mar", price: "R$ 2.450.000", cta: "Agendar visita",
      font: "Tahoma", stops: [{ c: "#141e30" }, { c: "#243b55" }], bgAngle: 180, align: "left", textColor: "#f5e6c8", accent: "#d4af37", ctaText: "#141e30", nameSize: 72, priceSize: 96, shadow: false } }
];
